FROM node:latest
MAINTAINER kareem <ka5089335@gmail.com>
COPY . .
EXPOSE 3000
RUN npm install 
CMD ["node", "app.js"]

# podman build -t [kemoimage]:[tag]   "dockerfile location" >> image
#podman run --name kemo -p 3000:3000 -d kemoimage:3.0  >> container 
	                                   #bta3t expose:bta3t el backed



