FROM mongo:latest

EXPOSE 27017

#podman build -t [kemoimage]:[tag]   "dockerfile location" >> image

#podman run --ip=5ana  <> "localhost" hatt4al bs fl backed

#ip addr show | grep "podman0" > a5tar network feha podman inet with ip 
#a5do w a8yr a5r 5ana 